# Site setings
title: "Ruby & Beyond"
description: "Igor Aleksandrov – Ruby engineer, Open Source contributor, JetRockets CTO and co-founder, Docker Captain and a proud father."
# logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
timezone: Asia/Tbilisi
url: https://igor.works
simple_analytics: true
page_excerpts: false
excerpt_separator: <!--more-->

# Author
author:
  name: "Igor Aleksandrov"
  image: "igor.jpeg"
  webp: "igor.webp"
  greetings: "Ruby & Beyond"
  description: "Hello, 👋. My name is Igor Aleksandrov.<br/>I am CTO of JetRockets, Docker Captain and a software engineer with more than 15 years of experience."
  bio: "I am a Ruby/Rails engineer, Open Source contributor, JetRockets CTO, and Docker Captain. I have been working with Ruby since 2008 and with Rails since 2009, and my overall commercial experience in programming is 20 years. I started working with Rails when it was at version 2.2 and never stopped since then."
  twitter: "igor_alexandrov"

# Contact form setings
email: igor.alexandrov@gmail.com
formspree_id: mqkrenkd
contact_page_description: 'If you have any questions or just want to say "Hi 👋", please feel free to drop me a line. I will try my best to respond as soon as possible!'
thankyou_page_description: "Your message has been successfully sent. I will contact you very soon!"

twitter:
  username: "igor_alexandrov"
  card: summary_large_image
github: "igor-alexandrov"
linkedin: "igor-aleksandrov"
youtube: "@RubyAndBeyond"

# Navigation
navigation:
  - text: Public Speeches
    url: /public-speeches
  # - text: What to Learn
  #   url: /what-to-learn
  - text: About
    url: /about
  - text: Archive
    url: /archive
  - text: Contact Me
    url: /contact-me

include:
  - robots.txt

exclude:
  - bin
  - config
  - vite.config.ts
  - tmp
  - Procfile.dev
  - Rakefile
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Required Plugins
plugins:
  - jekyll/vite
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-og-image
  - jekyll-target-blank
  - jekyll-toc

# Pagination
paginate: 5
paginate_path: /page-:num/

# Permalinks
permalink: /blog/:title

# Other
markdown: kramdown
highlighter: nil
# kramdown:
#   input: GFM

toc:
  max_level: 3
  list_class: ""

og_image:
  output_dir: "/assets/og"
  image: "/assets/images/igor.jpeg"
  canvas:
    background_color: "#FFFFFF"
    # background_image: "/assets/images/bc_3.jpg"
  header:
    font_family: "Roboto, Bold"
    color: "#333333"
  content:
    font_family: "Roboto, Regular"
    color: "#333333"
  force: false
  domain: "igor.works"
  border_bottom:
    width: 20
    fill:
      - "#65ADFF"
      - "#AD74B4"
      - "#EBB7A7"
      - "#F0D600"
      - "#CE4622"
      - "#1624C2"
      - "#EAD6E1"
      - "#EC549F"
      - "#00841C"
