# Site setings
name: "Ruby & Beyond"
description: "Ruby/Crystal developer, Open Source contributor, JetRockets CTO and co-founder, and a proud father."
meta_description: "Igor Alexandrov – Ruby/Crystal developer, Open Source contributor, JetRockets CTO and co-founder, and a proud father."
# logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
timezone: Asia/Tbilisi
# baseurl: <%= ENV['JEKYLL_ENV'] == 'production' ? 'https://igor.works' : 'http://localhost:4000' %>
# production_url: https://igor.works/
disqus: "igor-alexandrov"
# mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
cover_image: bc_3.jpg
# Add your GA Tracking Id
ga_analytics:

# Author
author:
  name: "Igor Alexandrov"
  image: "igor.jpeg"
  greetings: "Ruby & Beyond"
  description: "My name is Igor Alexandrov.<br/>I am CTO of JetRockets and a software engineer with more than 15 years of experience."
  bio: "Igor is a Ruby/Rails and Crystal engineer, Open Source contributor, JetRockets CTO and co-founder, and a proud father."
  twitter: "@igor_alexandrov"

# Contact form setings
email: igor.alexandrov@gmail.com
formspree_id: mqkrenkd
contact_page_description: "If you have any questions or just want to say \"Hi 👋\", please feel free to drop me a line. I will try my best to respond as soon as possible!"
thankyou_page_description: "Your message has been successfully sent. I will contact you very soon!"

# Social links
twitter:
  username: "igor_alexandrov"
  card: summary
# facebook: "username"
github: "igor-alexandrov"
# codepen: "username"
# dribbble: "username"
# medium: "@username"
# instagram: "username"
# pinterest: "username"
linkedin: "igor-alexandrov"
# producthunt: "@username"

# Navigation
navigation:
  - text: Speaking Opportunities
    url: /speaking-opportunities
  - text: About
    url: /about
  - text: Archive
    url: /archive
  - text: Contact Me
    url: /contact-me
  # - text: Style Guide
  #   url: /style-guide

include:
  - robots.txt

exclude:
  - config
  - bin
  - vite.config.ts
  - Procfile.dev
  - Rakefile

# # Required Plugins
# plugins_dir:
#   - jekyll-paginate
#   - jekyll-seo-tag
#   - jekyll-sitemap

plugins:
  - jekyll/vite
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /blog/:title

# Other
markdown: kramdown