# Site Info
title:              "Igor Alexandrov"
description:        "Ruby/Crystal developer, Open Source contributor, [JetRockets](https://jetrockets.com) CTO and co-founder, and a proud father."
author_name:        "Igor Alexandrov" # change this to your name
logo_url:           assets/img/avatar.jpg

# Site Settings
url:                https://igor-alexandrov.github.io # main url
# baseurl:            /the-plain
permalink:          /:title # Post permalink
timezone:           Asia/Tbilisi # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
